# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/reg/Paper/demo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/reg/Paper/demo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/reg/Paper/demo/CMakeFiles /home/reg/Paper/demo//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/reg/Paper/demo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GenerateParser

# Build rule for target.
GenerateParser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GenerateParser
.PHONY : GenerateParser

# fast build rule for target.
GenerateParser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GenerateParser.dir/build.make CMakeFiles/GenerateParser.dir/build
.PHONY : GenerateParser/fast

#=============================================================================
# Target rules for targets named antlr4-demo

# Build rule for target.
antlr4-demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 antlr4-demo
.PHONY : antlr4-demo

# fast build rule for target.
antlr4-demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/build
.PHONY : antlr4-demo/fast

# target to build an object file
Linux/main.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/Linux/main.o
.PHONY : Linux/main.o

# target to preprocess a source file
Linux/main.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/Linux/main.i
.PHONY : Linux/main.i

# target to generate assembly for a file
Linux/main.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/Linux/main.s
.PHONY : Linux/main.s

# target to build an object file
generated/TLexer.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/TLexer.o
.PHONY : generated/TLexer.o

# target to preprocess a source file
generated/TLexer.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/TLexer.i
.PHONY : generated/TLexer.i

# target to generate assembly for a file
generated/TLexer.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/TLexer.s
.PHONY : generated/TLexer.s

# target to build an object file
generated/TParser.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/TParser.o
.PHONY : generated/TParser.o

# target to preprocess a source file
generated/TParser.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/TParser.i
.PHONY : generated/TParser.i

# target to generate assembly for a file
generated/TParser.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/TParser.s
.PHONY : generated/TParser.s

# target to build an object file
generated/TParserBaseListener.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/TParserBaseListener.o
.PHONY : generated/TParserBaseListener.o

# target to preprocess a source file
generated/TParserBaseListener.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/TParserBaseListener.i
.PHONY : generated/TParserBaseListener.i

# target to generate assembly for a file
generated/TParserBaseListener.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/TParserBaseListener.s
.PHONY : generated/TParserBaseListener.s

# target to build an object file
generated/TParserBaseVisitor.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/TParserBaseVisitor.o
.PHONY : generated/TParserBaseVisitor.o

# target to preprocess a source file
generated/TParserBaseVisitor.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/TParserBaseVisitor.i
.PHONY : generated/TParserBaseVisitor.i

# target to generate assembly for a file
generated/TParserBaseVisitor.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/TParserBaseVisitor.s
.PHONY : generated/TParserBaseVisitor.s

# target to build an object file
generated/TParserListener.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/TParserListener.o
.PHONY : generated/TParserListener.o

# target to preprocess a source file
generated/TParserListener.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/TParserListener.i
.PHONY : generated/TParserListener.i

# target to generate assembly for a file
generated/TParserListener.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/TParserListener.s
.PHONY : generated/TParserListener.s

# target to build an object file
generated/TParserVisitor.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/TParserVisitor.o
.PHONY : generated/TParserVisitor.o

# target to preprocess a source file
generated/TParserVisitor.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/TParserVisitor.i
.PHONY : generated/TParserVisitor.i

# target to generate assembly for a file
generated/TParserVisitor.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/TParserVisitor.s
.PHONY : generated/TParserVisitor.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... GenerateParser"
	@echo "... antlr4-demo"
	@echo "... Linux/main.o"
	@echo "... Linux/main.i"
	@echo "... Linux/main.s"
	@echo "... generated/TLexer.o"
	@echo "... generated/TLexer.i"
	@echo "... generated/TLexer.s"
	@echo "... generated/TParser.o"
	@echo "... generated/TParser.i"
	@echo "... generated/TParser.s"
	@echo "... generated/TParserBaseListener.o"
	@echo "... generated/TParserBaseListener.i"
	@echo "... generated/TParserBaseListener.s"
	@echo "... generated/TParserBaseVisitor.o"
	@echo "... generated/TParserBaseVisitor.i"
	@echo "... generated/TParserBaseVisitor.s"
	@echo "... generated/TParserListener.o"
	@echo "... generated/TParserListener.i"
	@echo "... generated/TParserListener.s"
	@echo "... generated/TParserVisitor.o"
	@echo "... generated/TParserVisitor.i"
	@echo "... generated/TParserVisitor.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

