# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/kn/rcc

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/kn/rcc

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kn/rcc/CMakeFiles /home/kn/rcc//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/kn/rcc/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GenerateParser

# Build rule for target.
GenerateParser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 GenerateParser
.PHONY : GenerateParser

# fast build rule for target.
GenerateParser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/GenerateParser.dir/build.make CMakeFiles/GenerateParser.dir/build
.PHONY : GenerateParser/fast

#=============================================================================
# Target rules for targets named antlr4-demo

# Build rule for target.
antlr4-demo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 antlr4-demo
.PHONY : antlr4-demo

# fast build rule for target.
antlr4-demo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/build
.PHONY : antlr4-demo/fast

generated/ANTLR/TLexer.o: generated/ANTLR/TLexer.cpp.o
.PHONY : generated/ANTLR/TLexer.o

# target to build an object file
generated/ANTLR/TLexer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/ANTLR/TLexer.cpp.o
.PHONY : generated/ANTLR/TLexer.cpp.o

generated/ANTLR/TLexer.i: generated/ANTLR/TLexer.cpp.i
.PHONY : generated/ANTLR/TLexer.i

# target to preprocess a source file
generated/ANTLR/TLexer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/ANTLR/TLexer.cpp.i
.PHONY : generated/ANTLR/TLexer.cpp.i

generated/ANTLR/TLexer.s: generated/ANTLR/TLexer.cpp.s
.PHONY : generated/ANTLR/TLexer.s

# target to generate assembly for a file
generated/ANTLR/TLexer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/ANTLR/TLexer.cpp.s
.PHONY : generated/ANTLR/TLexer.cpp.s

generated/ANTLR/TParser.o: generated/ANTLR/TParser.cpp.o
.PHONY : generated/ANTLR/TParser.o

# target to build an object file
generated/ANTLR/TParser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/ANTLR/TParser.cpp.o
.PHONY : generated/ANTLR/TParser.cpp.o

generated/ANTLR/TParser.i: generated/ANTLR/TParser.cpp.i
.PHONY : generated/ANTLR/TParser.i

# target to preprocess a source file
generated/ANTLR/TParser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/ANTLR/TParser.cpp.i
.PHONY : generated/ANTLR/TParser.cpp.i

generated/ANTLR/TParser.s: generated/ANTLR/TParser.cpp.s
.PHONY : generated/ANTLR/TParser.s

# target to generate assembly for a file
generated/ANTLR/TParser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/ANTLR/TParser.cpp.s
.PHONY : generated/ANTLR/TParser.cpp.s

generated/ANTLR/TParserBaseListener.o: generated/ANTLR/TParserBaseListener.cpp.o
.PHONY : generated/ANTLR/TParserBaseListener.o

# target to build an object file
generated/ANTLR/TParserBaseListener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/ANTLR/TParserBaseListener.cpp.o
.PHONY : generated/ANTLR/TParserBaseListener.cpp.o

generated/ANTLR/TParserBaseListener.i: generated/ANTLR/TParserBaseListener.cpp.i
.PHONY : generated/ANTLR/TParserBaseListener.i

# target to preprocess a source file
generated/ANTLR/TParserBaseListener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/ANTLR/TParserBaseListener.cpp.i
.PHONY : generated/ANTLR/TParserBaseListener.cpp.i

generated/ANTLR/TParserBaseListener.s: generated/ANTLR/TParserBaseListener.cpp.s
.PHONY : generated/ANTLR/TParserBaseListener.s

# target to generate assembly for a file
generated/ANTLR/TParserBaseListener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/ANTLR/TParserBaseListener.cpp.s
.PHONY : generated/ANTLR/TParserBaseListener.cpp.s

generated/ANTLR/TParserBaseVisitor.o: generated/ANTLR/TParserBaseVisitor.cpp.o
.PHONY : generated/ANTLR/TParserBaseVisitor.o

# target to build an object file
generated/ANTLR/TParserBaseVisitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/ANTLR/TParserBaseVisitor.cpp.o
.PHONY : generated/ANTLR/TParserBaseVisitor.cpp.o

generated/ANTLR/TParserBaseVisitor.i: generated/ANTLR/TParserBaseVisitor.cpp.i
.PHONY : generated/ANTLR/TParserBaseVisitor.i

# target to preprocess a source file
generated/ANTLR/TParserBaseVisitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/ANTLR/TParserBaseVisitor.cpp.i
.PHONY : generated/ANTLR/TParserBaseVisitor.cpp.i

generated/ANTLR/TParserBaseVisitor.s: generated/ANTLR/TParserBaseVisitor.cpp.s
.PHONY : generated/ANTLR/TParserBaseVisitor.s

# target to generate assembly for a file
generated/ANTLR/TParserBaseVisitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/ANTLR/TParserBaseVisitor.cpp.s
.PHONY : generated/ANTLR/TParserBaseVisitor.cpp.s

generated/ANTLR/TParserListener.o: generated/ANTLR/TParserListener.cpp.o
.PHONY : generated/ANTLR/TParserListener.o

# target to build an object file
generated/ANTLR/TParserListener.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/ANTLR/TParserListener.cpp.o
.PHONY : generated/ANTLR/TParserListener.cpp.o

generated/ANTLR/TParserListener.i: generated/ANTLR/TParserListener.cpp.i
.PHONY : generated/ANTLR/TParserListener.i

# target to preprocess a source file
generated/ANTLR/TParserListener.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/ANTLR/TParserListener.cpp.i
.PHONY : generated/ANTLR/TParserListener.cpp.i

generated/ANTLR/TParserListener.s: generated/ANTLR/TParserListener.cpp.s
.PHONY : generated/ANTLR/TParserListener.s

# target to generate assembly for a file
generated/ANTLR/TParserListener.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/ANTLR/TParserListener.cpp.s
.PHONY : generated/ANTLR/TParserListener.cpp.s

generated/ANTLR/TParserVisitor.o: generated/ANTLR/TParserVisitor.cpp.o
.PHONY : generated/ANTLR/TParserVisitor.o

# target to build an object file
generated/ANTLR/TParserVisitor.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/ANTLR/TParserVisitor.cpp.o
.PHONY : generated/ANTLR/TParserVisitor.cpp.o

generated/ANTLR/TParserVisitor.i: generated/ANTLR/TParserVisitor.cpp.i
.PHONY : generated/ANTLR/TParserVisitor.i

# target to preprocess a source file
generated/ANTLR/TParserVisitor.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/ANTLR/TParserVisitor.cpp.i
.PHONY : generated/ANTLR/TParserVisitor.cpp.i

generated/ANTLR/TParserVisitor.s: generated/ANTLR/TParserVisitor.cpp.s
.PHONY : generated/ANTLR/TParserVisitor.s

# target to generate assembly for a file
generated/ANTLR/TParserVisitor.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/generated/ANTLR/TParserVisitor.cpp.s
.PHONY : generated/ANTLR/TParserVisitor.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/antlr4-demo.dir/build.make CMakeFiles/antlr4-demo.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... GenerateParser"
	@echo "... antlr4-demo"
	@echo "... generated/ANTLR/TLexer.o"
	@echo "... generated/ANTLR/TLexer.i"
	@echo "... generated/ANTLR/TLexer.s"
	@echo "... generated/ANTLR/TParser.o"
	@echo "... generated/ANTLR/TParser.i"
	@echo "... generated/ANTLR/TParser.s"
	@echo "... generated/ANTLR/TParserBaseListener.o"
	@echo "... generated/ANTLR/TParserBaseListener.i"
	@echo "... generated/ANTLR/TParserBaseListener.s"
	@echo "... generated/ANTLR/TParserBaseVisitor.o"
	@echo "... generated/ANTLR/TParserBaseVisitor.i"
	@echo "... generated/ANTLR/TParserBaseVisitor.s"
	@echo "... generated/ANTLR/TParserListener.o"
	@echo "... generated/ANTLR/TParserListener.i"
	@echo "... generated/ANTLR/TParserListener.s"
	@echo "... generated/ANTLR/TParserVisitor.o"
	@echo "... generated/ANTLR/TParserVisitor.i"
	@echo "... generated/ANTLR/TParserVisitor.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

